version: '2'

services:

  docker-av:
    #build: ./
    image: cheewai/docker-antivirus
    container_name: docker-av
    # uncomment and set the email address to receive email alerts when viruses are detected
    #command:
    # - /usr/local/install_alerts.sh email@example.net
    # - /usr/local/bin/duoscan.sh /path/to/scan
    volumes:
      # chmod ugo+w
      - ./clamav:/var/lib/clamav
      - ./maldetect:/usr/local/maldetect
